import { execa } from "execa";

export class GitManager {
  /**
   * Resiliently fetches current branch even in 0-commit repos
   */
  public static async getCurrentBranch(): Promise<string> {
    try {
      const { stdout } = await execa("git", ["rev-parse", "--abbrev-ref", "HEAD"]);
      return stdout.trim();
    } catch {
      try {
        const { stdout } = await execa("git", ["symbolic-ref", "--short", "HEAD"]);
        return stdout.trim();
      } catch {
        return "main";
      }
    }
  }

  public static async hasCommits(): Promise<boolean> {
    try {
      await execa("git", ["rev-parse", "--verify", "HEAD"]);
      return true;
    } catch {
      return false;
    }
  }

  public static async isWorkingTreeClean(): Promise<boolean> {
    const { stdout } = await execa("git", ["status", "--porcelain"]);
    return stdout.trim().length === 0;
  }

  public static async getWorkingTreeDiff(): Promise<string> {
    try {
      const { stdout: diff } = await execa("git", ["diff", "HEAD"]);
      return diff;
    } catch {
      const { stdout: diff } = await execa("git", ["diff"]);
      return diff;
    }
  }

  public static async ensureTaskBranch(taskId: string, titleSlug: string): Promise<string> {
    const targetBranch = `task/${taskId.toLowerCase()}-${titleSlug.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
    const currentBranch = await this.getCurrentBranch();

    if (currentBranch === targetBranch) {
      return currentBranch;
    }

    const hasCommits = await this.hasCommits();

    if (!hasCommits) {
      // In a 0-commit repo, rename the initial unborn branch
      await execa("git", ["checkout", "-b", targetBranch]);
      return targetBranch;
    }

    // Check if branch already exists
    const { stdout: branches } = await execa("git", ["branch", "--list", targetBranch]);
    if (branches.trim().length > 0) {
      await execa("git", ["checkout", targetBranch]);
    } else {
      await execa("git", ["checkout", "-b", targetBranch]);
    }

    return targetBranch;
  }

  public static async getChangedFiles(): Promise<string[]> {
    const hasCommits = await this.hasCommits();

    if (!hasCommits) {
      // In 0-commit repos, list all untracked/staged files
      const { stdout: files } = await execa("git", ["status", "--porcelain"]);
      return files
        .split("\n")
        .map((line) => line.trim().slice(3).trim())
        .filter((f) => f.length > 0);
    }

    const { stdout: staged } = await execa("git", ["diff", "--name-only", "--cached"]);
    const { stdout: unstaged } = await execa("git", ["diff", "--name-only"]);
    const { stdout: untracked } = await execa("git", ["ls-files", "--others", "--exclude-standard"]);

    const allChanged = new Set([
      ...staged.split("\n"),
      ...unstaged.split("\n"),
      ...untracked.split("\n"),
    ]);

    return Array.from(allChanged).filter((f) => f.trim().length > 0);
  }

  public static async validateFileBoundaries(allowedFiles: string[]): Promise<{
    valid: boolean;
    violatingFiles: string[];
  }> {
    const changedFiles = await this.getChangedFiles();
    const violatingFiles: string[] = [];

    // System and Adapter files generated by harness that shouldn't trip task boundaries
    const SYSTEM_PREFIXES = [
      ".harness/",
      ".opencode/",
      "opencode.json",
      "opencode.md",
      "antigravity.json",
      ".gitignore",
    ];

    for (const changed of changedFiles) {
      if (SYSTEM_PREFIXES.some((prefix) => changed.startsWith(prefix) || changed === prefix)) {
        continue;
      }

      const isAllowed = allowedFiles.some((allowed) => {
        if (allowed === changed) return true;
        if (allowed.endsWith("/**") && changed.startsWith(allowed.replace("/**", ""))) return true;
        return false;
      });

      if (!isAllowed) {
        violatingFiles.push(changed);
      }
    }

    return {
      valid: violatingFiles.length === 0,
      violatingFiles,
    };
  }

  public static async checkpointStash(taskId: string): Promise<string> {
    const stashBranch = `stash/${taskId.toLowerCase()}-checkpoint-${Date.now()}`;
    await execa("git", ["checkout", "-b", stashBranch]);
    await execa("git", ["add", "."]);
    await execa("git", ["commit", "-m", `harness: checkpoint for ${taskId}`]);
    return stashBranch;
  }

  public static async rollbackAllowedFiles(allowedFiles: string[]): Promise<void> {
    for (const file of allowedFiles) {
      try {
        await execa("git", ["checkout", "HEAD", "--", file]);
      } catch {
        try {
          await execa("rm", ["-f", file]);
        } catch {}
      }
    }
  }
}