export class TemplateScaffolder {
	public static getCoreSkills(): Record<string, string> {
		return {
			"skill-harness.md": [
				"# Skill: AI Workflow Harness Meta-Framework",
				"",
				"## Objective",
				"Operate the 2-tier XP workflow, SQLite spec engine, boundary enforcement, and circuit breaker gates.",
				"",
				"## 1. Core Architecture Invariants",
				"- **2-Tier XP Planning:** Tier 1 (`harness init` / `harness analyze`) for brownfield discovery and project vision; Tier 2 (`harness feature <name>`) for 1-pass Agile feature slicing.",
				"- **2-Level Context Caching:** Always load `.harness/spec/app-summary.md` first. Load sub-specs (`business/`, `ui/`, `technical/`) only when implementing that specific feature.",
				"- **File Boundary Isolation:** Modify ONLY files listed in `## 1. Allowed File Boundaries` of the active task manifest (`.harness/tasks/task-XXX.md`). Maximum 2 allowed files per task.",
				"- **Deterministic Verification:** Require test exit code 0 (`harness verify`) before setting task status to `DONE`.",
				"- **3-Strike Circuit Breaker:** 3 consecutive test/verification failures trigger automated Git rollback to stash checkpoint.",
				"",
				"## 2. CLI Engines & Workflow Commands",
				"- `harness init` — Scaffold 17 directories, agent configurations, skills, and seed SQLite spec database.",
				"- `harness analyze` — Scan brownfield repositories and extract core modules without interactive prompts.",
				"- `harness feature <name> --files <paths>` — Generate atomic task manifest with risk level evaluation.",
				"- `harness start <task-id>` — Create git branch `task/<id>` and transition status to `IN_PROGRESS`.",
				"- `harness preflight <task-id>` — AST boundary check, working tree cleanliness, and secret scanning.",
				"- `harness verify <task-id>` — Execute test/lint suite, sanitize error cards, enforce exit-0 gate.",
				"- `harness close <task-id>` — Complete task, write spawn-log receipt, transition status to `DONE`.",
			].join("\n"),

			"skill-caveman.md": [
				"# Skill: Caveman Communication Mode",
				"",
				"## Objective",
				"Ultra-compressed communication mode. Cuts output tokens ~65% while keeping full technical accuracy and code completeness. Supports intensity levels: lite, full (default), ultra, wenyan-lite, wenyan-full, wenyan-ultra.",
				"",
				"Respond terse like smart caveman. All technical substance stay. Only fluff die.",
				"",
				"## 1. Persistence",
				"ACTIVE EVERY RESPONSE. No revert after many turns. No filler drift. Still active if unsure. Off only: 'stop caveman' / 'normal mode'. Default: **full**. Switch: `/caveman lite|full|ultra|wenyan-lite|wenyan-full|wenyan-ultra|off`.",
				"",
				"## 2. Operational Rules",
				"- **Drop:** Articles (a/an/the), filler (just/really/basically/actually/simply), pleasantries (sure/certainly/of course/happy to), hedging.",
				"- **Fragments OK:** Short synonyms (big not extensive, fix not 'implement a solution for').",
				"- **No Tool-Call Narration:** Fire direct. No preamble, plan, or progress note before or between calls. After result: next call direct or final answer — never announce next call.",
				"- **No Decorative Elements:** No decorative tables/emoji, no dumping long raw error logs unless asked — quote shortest decisive line.",
				"- **No Invented Abbreviations:** Standard well-known tech acronyms OK (DB/API/HTTP); NEVER invent new abbreviations (cfg/impl/req/res/fn) — tokenizer splits them same as full word: zero token saved, reader still decode.",
				"- **No Causal Arrows:** No arrows (-> or =>) in prose — own token, save nothing.",
				"- **Never Drop Negations:** Never drop not/never/no/only/except — flip meaning worse than any token saved. Numbers, units exact.",
				"- **Never ADD Word to Sound Caveman:** Compression only — style never grow output. No inserted pronoun or copula to fake broken grammar. Keep correct verb form when correct form cost same.",
				"- **Language Preservation:** Preserve user's dominant language exactly — reply in the language user writes, never switch. Compress the style, not the language. ALWAYS keep technical terms, code, API names, CLI commands, commit keywords verbatim.",
				"- **No Self-Reference:** Never name or announce the style. No 'caveman mode on', 'me caveman think', no third-person caveman tags.",
				"- **Pattern:** `[thing] [action] [reason]. [next step].`",
				"",
				"## 3. Intensity Matrix",
				"| Level | What change |",
				"|---|---|",
				"| **lite** | No filler/hedging. Keep articles + full sentences. Professional but tight |",
				"| **full** | Drop articles, fragments OK, short synonyms. Classic caveman. No tool-call narration, no decorative tables/emoji, no long raw error logs unless asked. Standard acronyms OK |",
				"| **ultra** | Strip conjunctions when cause-then-effect stay unambiguous. One word when one word enough. State each fact once. NO prose abbreviations (cfg/impl/req/res/fn), NO arrows (X -> Y). Code symbols, function names, API names, error strings: never touch |",
				"| **wenyan-lite** | Semi-classical. Drop filler/hedging but keep grammar structure, classical register |",
				"| **wenyan-full** | Maximum classical terseness. Fully 文言文. 80-90% character reduction |",
				"| **wenyan-ultra** | Extreme abbreviation while keeping classical Chinese feel. Maximum compression |",
				"",
				"## 4. Auto-Clarity Exceptions",
				"Drop caveman temporarily for:",
				"- Security warnings",
				"- Irreversible action confirmations",
				"- Multi-step sequences where fragment order or omitted conjunctions risk misread",
				"- Compression itself creates technical ambiguity",
				"- User asks to clarify or repeats question",
				"*(Resume caveman immediately after clear warning/confirmation done)*",
				"",
				"## 5. External Boundaries",
				"Persisted outside chat: write normal prose — code, comments, commits, docs, issue/PR/MR text, memory files, third-party messages. Body going to other humans must be normal English.",
			].join("\n"),

			"skill-context-caching.md": [
				"# Skill: 2-Level Context Window Caching",
				"",
				"## Objective",
				"Minimize prompt cost across multi-turn agent sessions using structured specification layering.",
				"",
				"## Caching Protocol",
				"1. **Level 1 (Anchor):** Always load `.harness/spec/app-summary.md` into the prompt context on session start.",
				"2. **Level 2 (Demand):** Drill down to `.harness/spec/features/<feature>/README.md` and sub-specs (`business/`, `ui/`, `technical/`) ONLY when actively implementing that feature.",
				"3. **Zero Unneeded Files:** Never load unreferenced source files or entire directories into the context window.",
			].join("\n"),

			"skill-wayfinder-harness.md": [
				"# Skill: Wayfinder Planning (Harness-Adapted)",
				"",
				"## Objective",
				"Chart large planning efforts by creating discovery Maps at `.harness/memory/discovery/<feature>-map.md`, then resolving decision tickets one at a time until the way is clear.",
				"",
				"## Core Rules",
				"- Plan, don't code: Produce decisions and specifications, not implementation code.",
				"- Wayfinder Grilling (3+2 Choice Rule): @architect-agent MUST ask structured questions presenting 3 recommended options, Option 4 (Other write-in), and Option 5 (Explain / Need context).",
				"- Discovery Map Structure:",
				"  - Destination: High-level goal and success criteria.",
				"  - Notes: Key context, user constraints, stack preferences.",
				"  - Decisions So Far: Confirmed technical and business choices.",
				"  - Fog of War: Undecided requirements (ticketed for resolution before slicing).",
				"  - Out of Scope: Explicitly excluded features/technologies.",
				"- Ticket Types:",
				"  - `research`: Broad codebase or market analysis (unbounded).",
				"  - `grilling`: Interactive user Q&A (3+2 choice rule).",
				"  - `spike`: Prototype implementation by @tech-lead (relaxed boundaries).",
				"  - `task`: Production implementation (≤2 allowed files).",
				"- Downstream Hand-Off:",
				"  - Phase 2 (PO) reads Decisions So Far to define epics/user journeys.",
				"  - Phase 4 (Architect) converts decisions into technical specs (`.harness/spec/features/<feature>/technical/spec.md`).",
				"  - Phase 5 (PO) slices resolved tickets into atomic task manifests (`.harness/tasks/task-XXX.md`).",
			].join("\n"),

			"skill-linear-cli.md": [
				"# Skill: Linear CLI Issue Management",
				"",
				"## Objective",
				"Manage Linear issues, teams, projects, and cycles from the command line using `linear` CLI tool.",
				"",
				"## Core Commands",
				"- List assigned issues: `linear issue list --assigned`",
				"- View issue details: `linear issue view <issue-id>`",
				"- Create new issue: `linear issue create --title \"<title>\" --description \"<desc>\"`",
				"- Update issue status: `linear issue update <issue-id> --state \"In Progress\"` (or \"Done\")",
				"- Comment on issue: `linear issue comment <issue-id> --body \"<message>\"` — use for status updates on task close.",
			].join("\n"),

			"skill-db-first-specs.md": [
				"# Skill: DB-First Specification Management (ADR-01)",
				"",
				"## Objective",
				"Operate the SQLite `.harness/harness.db` spec engine using the native `spec-query` MCP tool to query, insert, and update application specifications.",
				"",
				"## 1. Reading Specs via MCP (`spec-query`)",
				"- **List All Features:** Call `list_features()` to get all registered system features and their status.",
				"- **Get Feature Overview:** Call `get_feature_overview({ featureSlug: \"auth\" })` to inspect summary and topic categories.",
				"- **Get Specific Category Spec:** Call `get_spec({ featureSlug: \"auth\", category: \"business\", level: \"detail\" })` (categories: `business`, `ui`, `technical`, `pipeline`).",
				"- **Search Across Specs:** Call `search_specs({ query: \"jwt token authentication\" })` to perform full-text search across all spec chunks.",
				"",
				"## 2. DB Authoring & Inverted Context Window Protocol",
				"- Store all feature specs in SQLite `harness.db` (`features`, `spec_topics`, and `spec_chunks` tables).",
				"- Do NOT load raw markdown files into the prompt context. Query specs on-demand using `spec-query` MCP tool.",
				"- Un-gitignore `!harness.db` so database changes are committed directly to Git alongside source code diffs.",
			].join("\n"),
		};
	}

	public static getStackSkills(): Record<string, string> {
		return {
			"skill-tailwind-shadcn.md": [
				"# Skill: Tailwind CSS & Component Architecture",
				"",
				"## Rules & Invariants",
				"- Use utility-first Tailwind classes adhering strictly to established design system tokens.",
				"- Maintain accessibility attributes (`aria-*`, `role`, focus visible states) across all interactive elements.",
				"- Keep presentation logic separate from custom data hooks.",
				"- Support seamless dark mode and glassmorphism styling.",
			].join("\n"),

			"skill-tanstack-query.md": [
				"# Skill: TanStack Query Best Practices",
				"",
				"## Rules & Invariants",
				"- Declare standardized query keys using array tuples `['resource', id]`.",
				"- Implement optimistic updates for mutating actions with automatic rollback on error.",
				"- Centralize API fetchers in dedicated service modules with typed responses.",
			].join("\n"),

			"skill-expo-router.md": [
				"# Skill: Expo Router & React Native Architecture",
				"",
				"## Rules & Invariants",
				"- Follow file-based routing conventions inside `app/` directory.",
				"- Utilize `react-native-reanimated` for smooth 60fps UI transitions.",
				"- Ensure safe area insets are respected across iOS and Android viewports.",
			].join("\n"),

			"skill-typescript-strict.md": [
				"# Skill: Strict TypeScript & Zod Type Safety",
				"",
				"## Rules & Invariants",
				"- Enforce `strict: true` with ZERO usage of `any` (use `unknown` + type guards).",
				"- Derive runtime types from Zod schemas using `z.infer<typeof Schema>`.",
				"- Use discriminated unions for distinct application state representations.",
				"- Maintain explicit return types on all public export functions.",
			].join("\n"),

			"skill-idiomatic-go.md": [
				"# Skill: Idiomatic Golang Architecture",
				"",
				"## Rules & Invariants",
				"- Always accept `context.Context` as the first argument in I/O and database methods.",
				"- Explicitly wrap errors using `fmt.Errorf(\"action: %w\", err)`.",
				"- Use structured logging via standard library `log/slog`.",
			].join("\n"),

			"skill-sqlc.md": [
				"# Skill: sqlc Type-Safe SQL Queries",
				"",
				"## Rules & Invariants",
				"- Author pure SQL queries with annotated query names `-- name: GetUser :one`.",
				"- Run `sqlc generate` to produce type-safe Go structs without ORM overhead.",
			].join("\n"),

			"skill-postgres-schema-design.md": [
				"# Skill: PostgreSQL Schema & Migration Strategy",
				"",
				"## Rules & Invariants",
				"- All foreign keys must include explicit index coverage.",
				"- Author migrations with deterministic down/rollback scripts.",
				"- Use `TIMESTAMPTZ` for all temporal columns.",
			].join("\n"),

			"skill-dynamodb-single-table.md": [
				"# Skill: DynamoDB Single-Table Design",
				"",
				"## Rules & Invariants",
				"- Model access patterns before defining Partition (`PK`) and Sort (`SK`) keys.",
				"- Use composite sort keys with delimiters (e.g. `USER#123#METADATA`).",
			].join("\n"),
		};
	}

	public static getTestingSkills(): Record<string, string> {
		return {
			"skill-tdd-assertions.md": [
				"# Skill: Test-Driven Development (TDD) Assertions",
				"",
				"## Objective & Discipline",
				"Author comprehensive, failing test suites BEFORE any implementation code begins (RED phase of TDD).",
				"",
				"## Mandatory Assertion Rules",
				"1. **Happy Path:** Assert specific expected return values, payload structures, and side effects.",
				"2. **Sad Path FIRST:** Error handling is more important than happy path. Test invalid input rejection using specific error matchers (e.g. `toThrow()`).",
				"3. **No Soft Assertions:** Never use `toBeTruthy()` or `toBeDefined()` alone — assert exact values.",
				"4. **Isolation:** Mock external dependencies (filesystem, network, DB) — tests must run deterministically in isolated sandbox.",
			].join("\n"),

			"skill-zero-noise-reporter.md": [
				"# Skill: Zero-Noise Test Diagnostic Reporting",
				"",
				"## Objective",
				"Format test failures into concise, actionable diagnostic cards to prevent log pollution.",
				"",
				"## Diagnostic Card Format",
				"```",
				"┌────────────────────────────────────────────────────────┐",
				"│ ✖ TEST FAILURE: [Suite Name]                           │",
				"├────────────────────────────────────────────────────────┤",
				"│ Target File: <file-path>:<line-number>                  │",
				"│ Expected:    <expected-value>                          │",
				"│ Received:    <actual-value>                            │",
				"└────────────────────────────────────────────────────────┘",
				"```",
			].join("\n"),
		};
	}

	public static getPipelineStandards(): Record<string, string> {
		return {
			"summary.md": [
				"# Pipeline Standards Index",
				"",
				"> **5-Phase XP Planning Pipeline Rules & Invariants**",
				"",
				"## Phases Overview",
				"- **[Phase 1: Problem Discovery](phase-1-discovery.md)** — Wayfinder grilling (3+2 rule) led by @architect-agent",
				"- **[Phase 2: Functional Strategy](phase-2-strategy.md)** — User journeys & epics authored to SQLite harness.db by @po-agent",
				"- **[Phase 3: Design Architecture](phase-3-design.md)** — UI component registry & wireframes by @designer-lead",
				"- **[Phase 4: Technical Architecture](phase-4-architecture.md)** — API contracts, ADRs & DB schemas by @architect-agent",
				"- **[Phase 5: Task Slicing](phase-5-slicing.md)** — Atomic task manifests (<=2 allowed files) by @po-agent & @tech-lead",
			].join("\n"),

			"phase-1-discovery.md": [
				"# Phase 1: Problem Discovery & Baseline Audit",
				"",
				"## 1. Objective & Role",
				"Establish clear feature goals and non-negotiable architectural constraints BEFORE code implementation begins. Lead by @architect-agent.",
				"",
				"## 2. Interactive Wayfinder Grilling Protocol (3+2 Choice Rule)",
				"When interviewing the user, @architect-agent MUST use structured Q&A:",
				"- Present each question with **3 recommended options** + **Option 4: Write-in / Other** + **Option 5: Explain / Need context**.",
				"- Never ask open-ended ambiguous questions without concrete suggestions.",
				"- Resolve one branch of the decision tree at a time.",
				"",
				"## 3. Mandatory Phase 1 Deliverables",
				"1. **Discovery Map:** Saved to `.harness/memory/discovery/<feature>-map.md` containing:",
				"   - **Destination:** High-level feature goal and success criteria.",
				"   - **Notes:** Key context, user constraints, stack preferences.",
				"   - **Decisions So Far:** Confirmed technical and business choices.",
				"   - **Fog of War:** Undecided requirements (ticketed for resolution before slicing).",
				"   - **Out of Scope:** Explicitly excluded items.",
				"2. **Interview Transcript:** Saved to `.harness/memory/discovery/<feature>.md`.",
				"3. **Spec Database Feature Seed:** Upsert feature record into `.harness/harness.db` and export to `.harness/spec/app-summary.md`.",
				"",
				"## 4. Downstream Integration & Pipeline Usefulness",
				"- **Phase 2 (PO):** Reads Discovery Map to define epics and user journeys.",
				"- **Phase 4 (Architect):** Uses Decisions So Far to author technical specs (`.harness/spec/features/<feature>/technical/spec.md`).",
				"- **Phase 5 (PO):** Converts resolved tickets into atomic tasks (`.harness/tasks/task-XXX.md`).",
			].join("\n"),

			"phase-2-strategy.md": [
				"# Phase 2: Functional Scope & Workflow Strategy",
				"",
				"## 1. Objective & Role",
				"Translate Phase 1 Discovery Maps into user personas, epic boundaries, and validation rules. Lead by @po-agent.",
				"",
				"## 2. Execution Discipline",
				"- **User Journeys:** Define explicit persona entry points, action flows, and success outcomes.",
				"- **Epic Scope Boundaries:** Group functional requirements into coherent, non-overlapping epics.",
				"- **Topology Validation:** Confirm AI execution mode (`orchestrated`, `solo-agent`, or `vibe-assist`).",
				"- **Zero Code Rule:** @po-agent authors SPECIFICATIONS ONLY, never production source code.",
				"",
				"## 3. Deliverables",
				"- Write functional specification to `.harness/spec/features/<feature>/business/spec.md`.",
				"- Define acceptance criteria checklist for downstream task generation.",
			].join("\n"),

			"phase-3-design.md": [
				"# Phase 3: Visualization & Design Architecture",
				"",
				"## 1. Objective & Role",
				"Establish visual layout, component hierarchies, and interactive state flows before coding frontend features. Lead by @designer-lead & @designer-ui.",
				"",
				"## 2. Execution Discipline",
				"- **ASCII Wireframe Layouts:** Author structural ASCII component layouts in `wireframe-ascii.md`.",
				"- **Mermaid State Diagrams:** Model interactive UI transitions, loading states, and error flows in `route-flow-mermaid.md`.",
				"- **Design System Consistency:** Adhere strictly to Tailwind design tokens, typography, and color palettes.",
				"",
				"## 3. Deliverables",
				"- Register reusable components in `.harness/UI/custom-components-registry.ts`.",
				"- Write detailed component breakdown to `.harness/UI/details/<component-name>/spec.md`.",
				"- Write UI specification to `.harness/spec/features/<feature>/ui/spec.md`.",
			].join("\n"),

			"phase-4-architecture.md": [
				"# Phase 4: Technical Architecture & Contracts",
				"",
				"## 1. Objective & Role",
				"Design robust data schemas, type contracts, and API interface specifications. Lead by @architect-agent.",
				"",
				"## 2. Technical Invariants",
				"- **Strict Type Safety:** Derive runtime validation using Zod schemas with zero `any` usage.",
				"- **API Contracts:** Define exact payload shapes, HTTP status codes, and error response structures.",
				"- **Architectural Decision Records (ADRs):** Author lightweight ADRs for non-trivial tech stack or library choices.",
				"- **Zero-Code Rule:** @architect-agent authors SPECIFICATIONS ONLY, never production source code.",
				"",
				"## 3. Deliverables",
				"- Write technical specification to `.harness/spec/features/<feature>/technical/spec.md` (max 500 lines).",
				"- Define schema migration SQL / models in database layer.",
			].join("\n"),

			"phase-5-slicing.md": [
				"# Phase 5: User Story Slicing & Task Backlog",
				"",
				"## 1. Objective & Role",
				"Break down technical and UI specs into atomic, boundary-isolated execution tasks touching ≤2 files each. Lead by @po-agent & @tech-lead.",
				"",
				"## 2. Task Slicing Rules",
				"- **File Boundary Isolation:** Every task manifest MUST specify explicit allowed files in `## 1. Allowed File Boundaries`.",
				"- **Strict File Limit:** Maximum 2 allowed files per task to ensure small context window footprints.",
				"- **Negative-Proof Acceptance Criteria:** Include explicit happy-path AND error/boundary rejection criteria.",
				"- **Deterministic Verification:** Include explicit verification command block (e.g. `bun test <target>`).",
				"- **Git Commit Authority:** @tech-lead is sole Git commit authority upon 100% verification pass.",
				"",
				"## 3. Deliverables",
				"- Author atomic task manifests in `.harness/tasks/task-XXX.md`.",
				"- Set initial status to `TODO`.",
			].join("\n"),
		};
	}

	public static getUIComponentRegistryStarter(): string {
		return [
			"export interface UIComponentRecord {",
			"  name: string;",
			'  category: "atom" | "molecule" | "organism" | "template";',
			"  location: string;",
			"  description: string;",
			"  propsInterface?: string;",
			"  subComponents?: string[];",
			"  reusableAcross: string[];",
			"}",
			"",
			"export const CustomComponentsRegistry: UIComponentRecord[] = [];",
			"",
		].join("\n");
	}

	public static getRolesJson(): string {
		return JSON.stringify(
			{
				"architect-agent": {
					role: "architect",
					allowedTools: ["*"],
					allowedCategories: ["technical", "pipeline", "business"],
				},
				"po-agent": {
					role: "po",
					allowedTools: ["*"],
					allowedCategories: ["business", "pipeline", "tasks"],
				},
				"designer-lead": {
					role: "designer",
					allowedTools: ["*"],
					allowedCategories: ["ui"],
				},
				"tech-lead": {
					role: "tech-lead",
					allowedTools: ["*"],
					allowedCategories: ["tasks"],
				},
				"test-runner": {
					role: "test-runner",
					allowedTools: [
						"list_features",
						"get_feature_overview",
						"get_spec",
						"search_specs",
					],
				},
			},
			null,
			2,
		);
	}

	public static getCheckpointDbScript(): string {
		return [
			'import { Database } from "bun:sqlite";',
			'import path from "node:path";',
			"",
			'const dbPath = path.resolve(process.cwd(), ".harness/harness.db");',
			"const db = new Database(dbPath);",
			'db.exec("PRAGMA wal_checkpoint(TRUNCATE);");',
			"db.close();",
			'console.log("✔ harness.db WAL checkpoint complete (TRUNCATE).");',
		].join("\n");
	}

	public static getSeedFeaturesScript(): string {
		return [
			'import { Database } from "bun:sqlite";',
			'import fs from "node:fs/promises";',
			'import path from "node:path";',
			"",
			"async function seedFromDocs() {",
			'  const dbPath = path.resolve(process.cwd(), ".harness/harness.db");',
			"  const db = new Database(dbPath);",
			'  const docsDir = path.resolve(process.cwd(), "docs");',
			"  try {",
			"    const files = await fs.readdir(docsDir);",
			"    for (const file of files) {",
			'      if (file.endsWith(".md")) {',
			"        const raw = await fs.readFile(path.join(docsDir, file), \"utf-8\");",
			'        const slug = file.replace(".md", "").toLowerCase().replace(/[^a-z0-9]/g, "-");',
			'        const title = file.replace(".md", "");',
			'        const stmt = db.prepare("INSERT OR REPLACE INTO features (id, name, slug, summary, status) VALUES (?, ?, ?, ?, ?)");',
			'        stmt.run(`feat-${slug}`, title, slug, raw.slice(0, 150).replace(/\\n/g, " "), "STABLE");',
			"      }",
			"    }",
			"  } catch {}",
			'  db.exec("DELETE FROM spec_topics WHERE id NOT IN (SELECT DISTINCT topic_id FROM spec_chunks);");',
			'  db.exec("DELETE FROM features WHERE id NOT IN (SELECT DISTINCT feature_id FROM spec_topics);");',
			'  db.exec("PRAGMA wal_checkpoint(TRUNCATE);");',
			"  db.close();",
			'  console.log("✔ Seeded features to harness.db.");',
			"}",
			"seedFromDocs();",
		].join("\n");
	}

	public static getMigrateSpecsScript(): string {
		return [
			'import { Database } from "bun:sqlite";',
			'import fs from "node:fs/promises";',
			'import path from "node:path";',
			"",
			"async function migrateSpecs() {",
			'  const dbPath = path.resolve(process.cwd(), ".harness/harness.db");',
			"  const db = new Database(dbPath);",
			'  const specDir = path.resolve(process.cwd(), ".harness/spec/features");',
			"  try {",
			"    const featDirs = await fs.readdir(specDir);",
			"    for (const slug of featDirs) {",
			"      const featPath = path.join(specDir, slug);",
			"      const stat = await fs.stat(featPath);",
			"      if (stat.isDirectory()) {",
			'        for (const cat of ["business", "ui", "technical"] as const) {',
			'          const specFile = path.join(featPath, cat, "spec.md");',
			"          try {",
			'            const content = await fs.readFile(specFile, "utf-8");',
			'            const featRow = db.prepare("SELECT id FROM features WHERE slug = ?").get(slug) as any;',
			"            if (featRow) {",
			'              const topicId = `topic-${slug}-${cat}`;',
			'              db.prepare("INSERT OR REPLACE INTO spec_topics (id, feature_id, category, slug, title) VALUES (?, ?, ?, ?, ?)").run(topicId, featRow.id, cat, cat, `${cat} Spec`);',
			'              db.prepare("INSERT OR REPLACE INTO spec_chunks (id, topic_id, level, content, token_estimate) VALUES (?, ?, ?, ?, ?)").run(`chunk-${topicId}-detail`, topicId, "detail", content, Math.ceil(content.length / 4));',
			"            }",
			"          } catch {}",
			"        }",
			"      }",
			"    }",
			"  } catch {}",
			'  db.exec("DELETE FROM spec_topics WHERE id NOT IN (SELECT DISTINCT topic_id FROM spec_chunks);");',
			'  db.exec("DELETE FROM features WHERE id NOT IN (SELECT DISTINCT feature_id FROM spec_topics);");',
			'  db.exec("PRAGMA wal_checkpoint(TRUNCATE);");',
			"  db.close();",
			'  console.log("✔ Migrated specs into harness.db.");',
			"}",
			"migrateSpecs();",
		].join("\n");
	}

	public static getSpecQueryMcpServer(): string {
		return [
			'import { Database } from "bun:sqlite";',
			'import path from "node:path";',
			'import readline from "node:readline";',
			"",
			'const dbPath = path.resolve(process.cwd(), ".harness/harness.db");',
			"const db = new Database(dbPath);",
			"",
			"function checkpoint() {",
			'  try { db.exec("PRAGMA wal_checkpoint(TRUNCATE);"); } catch {}',
			"}",
			"",
			"const rl = readline.createInterface({",
			"  input: process.stdin,",
			"  output: process.stdout,",
			"  terminal: false,",
			"});",
			"",
			'rl.on("line", (line) => {',
			"  if (!line.trim()) return;",
			"  try {",
			"    const req = JSON.parse(line);",
			'    if (!req.id && req.method === "notifications/initialized") return;',
			"",
			"    let result: any = null;",
			"    let error: any = null;",
			"",
			'    if (req.method === "initialize") {',
			"      result = {",
			'        protocolVersion: "2024-11-05",',
			'        capabilities: { tools: {} },',
			'        serverInfo: { name: "spec-query", version: "2.0.0" },',
			"      };",
			'    } else if (req.method === "tools/list") {',
			"      result = {",
			"        tools: [",
			"          {",
			'            name: "list_features",',
			'            description: "List all registered system features and their status from SQLite spec database.",',
			'            inputSchema: { type: "object", properties: {} },',
			"          },",
			"          {",
			'            name: "get_feature_overview",',
			'            description: "Get summary and registered spec topics for a specific feature by slug.",',
			"            inputSchema: {",
			'              type: "object",',
			'              properties: { featureSlug: { type: "string", description: "Feature slug identifier" } },',
			'              required: ["featureSlug"],',
			"            },",
			"          },",
			"          {",
			'            name: "get_spec",',
			'            description: "Retrieve specification content for a feature by category (business, ui, technical, pipeline) and detail level.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                featureSlug: { type: "string", description: "Feature slug identifier" },',
			'                category: { type: "string", enum: ["business", "ui", "technical", "pipeline"] },',
			'                level: { type: "string", enum: ["summary", "detail"], default: "detail" },',
			"              },",
			'              required: ["featureSlug", "category"],',
			"            },",
			"          },",
			"          {",
			'            name: "search_specs",',
			'            description: "Perform full-text search across all spec topics and chunks in SQLite spec database.",',
			"            inputSchema: {",
			'              type: "object",',
			'              properties: { query: { type: "string", description: "Search query string" } },',
			'              required: ["query"],',
			"            },",
			"          },",
			"          {",
			'            name: "write_spec",',
			'            description: "Author or update a specification topic and chunk in SQLite spec database with auto WAL checkpointing.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                featureSlug: { type: "string", description: "Target feature slug" },',
			'                category: { type: "string", enum: ["business", "ui", "technical", "pipeline"] },',
			'                topicSlug: { type: "string", description: "Topic slug" },',
			'                title: { type: "string", description: "Topic title" },',
			'                content: { type: "string", description: "Specification markdown content" },',
			'                level: { type: "string", enum: ["summary", "detail"], default: "detail" },',
			"              },",
			'              required: ["featureSlug", "category", "topicSlug", "title", "content"],',
			"            },",
			"          },",
			"          {",
			'            name: "update_feature_status",',
			'            description: "Update the status of a registered feature in SQLite spec database.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                featureSlug: { type: "string", description: "Target feature slug" },',
			'                status: { type: "string", enum: ["DRAFT", "STABLE", "DEPRECATED"] },',
			"              },",
			'              required: ["featureSlug", "status"],',
			"            },",
			"          },",
			"          {",
			'            name: "create_task",',
			'            description: "Create a boundary-isolated task manifest entry in SQLite spec database.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                taskId: { type: "string", description: "Task ID (e.g. task-authlogin)" },',
			'                specSlug: { type: "string", description: "Associated feature slug" },',
			'                status: { type: "string", enum: ["TODO", "IN_PROGRESS", "VERIFYING", "DONE"], default: "TODO" },',
			'                allowedFiles: { type: "string", description: "Comma-separated allowed files (max 2)" },',
			'                acceptanceCriteria: { type: "string", description: "Acceptance criteria markdown checklist" },',
			"              },",
			'              required: ["taskId", "allowedFiles", "acceptanceCriteria"],',
			"            },",
			"          },",
			"          {",
			'            name: "update_task_status",',
			'            description: "Update task status in SQLite spec database.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                taskId: { type: "string", description: "Target task ID" },',
			'                status: { type: "string", enum: ["TODO", "IN_PROGRESS", "VERIFYING", "DONE"] },',
			"              },",
			'              required: ["taskId", "status"],',
			"            },",
			"          },",
			"        ],",
			"      };",
			'    } else if (req.method === "tools/call") {',
			"      const name = req.params?.name;",
			"      const args = req.params?.arguments || {};",
			'      if (name === "list_features") {',
			'        const rows = db.prepare("SELECT id, name, slug, summary, status FROM features ORDER BY name").all();',
			'        result = { content: [{ type: "text", text: JSON.stringify(rows, null, 2) }] };',
			'      } else if (name === "get_feature_overview") {',
			'        const slug = String(args?.featureSlug);',
			'        const feature = db.prepare("SELECT * FROM features WHERE slug = ?").get(slug);',
			'        if (!feature) {',
			'          result = { content: [{ type: "text", text: `Feature slug "${slug}" not found.` }] };',
			'        } else {',
			'          const topics = db.prepare("SELECT id, category, slug, title FROM spec_topics WHERE feature_id = (SELECT id FROM features WHERE slug = ?)").all(slug);',
			'          result = { content: [{ type: "text", text: JSON.stringify({ feature, topics }, null, 2) }] };',
			'        }',
			'      } else if (name === "get_spec") {',
			'        const slug = String(args?.featureSlug);',
			'        const category = String(args?.category);',
			'        const level = String(args?.level || "detail");',
			'        const query = db.prepare(`',
			'          SELECT t.title, t.category, c.level, c.content FROM spec_chunks c',
			'          JOIN spec_topics t ON c.topic_id = t.id',
			'          JOIN features f ON t.feature_id = f.id',
			'          WHERE f.slug = ? AND (t.category = ? OR t.slug = ?) AND c.level = ?',
			'        `);',
			'        const rows = query.all(slug, category, category, level);',
			'        if (!rows.length) {',
			'          result = { content: [{ type: "text", text: `No ${level} specs found for ${slug}/${category}.` }] };',
			'        } else {',
			'          result = { content: [{ type: "text", text: JSON.stringify(rows, null, 2) }] };',
			'        }',
			'      } else if (name === "search_specs") {',
			'        const q = `%${String(args?.query)}%`;',
			'        const rows = db.prepare(`',
			'          SELECT f.name as feature, t.category, t.title, c.content FROM spec_chunks c',
			'          JOIN spec_topics t ON c.topic_id = t.id',
			'          JOIN features f ON t.feature_id = f.id',
			'          WHERE t.title LIKE ? OR c.content LIKE ?',
			'          LIMIT 20',
			'        `).all(q, q);',
			'        result = { content: [{ type: "text", text: JSON.stringify(rows, null, 2) }] };',
			'      } else if (name === "write_spec") {',
			'        const slug = String(args?.featureSlug);',
			'        const category = String(args?.category);',
			'        const topicSlug = String(args?.topicSlug);',
			'        const title = String(args?.title);',
			'        const content = String(args?.content);',
			'        const level = String(args?.level || "detail");',
			'        const feat = db.prepare("SELECT id FROM features WHERE slug = ?").get(slug) as any;',
			'        if (!feat) {',
			'          result = { content: [{ type: "text", text: `Error: Feature "${slug}" not found in database.` }] };',
			'        } else {',
			'          const topicId = `topic-${slug}-${topicSlug}`;',
			'          db.prepare("INSERT OR REPLACE INTO spec_topics (id, feature_id, category, slug, title) VALUES (?, ?, ?, ?, ?)").run(topicId, feat.id, category, topicSlug, title);',
			'          db.prepare("INSERT OR REPLACE INTO spec_chunks (id, topic_id, level, content, token_estimate) VALUES (?, ?, ?, ?, ?)").run(`chunk-${topicId}-${level}`, topicId, level, content, Math.ceil(content.length / 4));',
			'          checkpoint();',
			'          result = { content: [{ type: "text", text: `✔ Successfully wrote spec for ${slug}/${category}/${topicSlug} (WAL checkpointed).` }] };',
			'        }',
			'      } else if (name === "update_feature_status") {',
			'        const slug = String(args?.featureSlug);',
			'        const status = String(args?.status);',
			'        db.prepare("UPDATE features SET status = ? WHERE slug = ?").run(status, slug);',
			'        checkpoint();',
			'        result = { content: [{ type: "text", text: `✔ Updated feature "${slug}" status to ${status}.` }] };',
			'      } else if (name === "create_task") {',
			'        const taskId = String(args?.taskId);',
			'        const specSlug = String(args?.specSlug || "");',
			'        const status = String(args?.status || "TODO");',
			'        const allowedFiles = String(args?.allowedFiles);',
			'        const acceptanceCriteria = String(args?.acceptanceCriteria);',
			'        const feat = specSlug ? (db.prepare("SELECT id FROM features WHERE slug = ?").get(specSlug) as any) : null;',
			'        db.prepare("INSERT OR REPLACE INTO tasks (id, spec_id, status, allowed_files, acceptance_criteria) VALUES (?, ?, ?, ?, ?)").run(taskId, feat?.id || null, status, allowedFiles, acceptanceCriteria);',
			'        checkpoint();',
			'        result = { content: [{ type: "text", text: `✔ Task "${taskId}" created/updated in database.` }] };',
			'      } else if (name === "update_task_status") {',
			'        const taskId = String(args?.taskId);',
			'        const status = String(args?.status);',
			'        db.prepare("UPDATE tasks SET status = ? WHERE id = ?").run(status, taskId);',
			'        checkpoint();',
			'        result = { content: [{ type: "text", text: `✔ Updated task "${taskId}" status to ${status}.` }] };',
			'      } else {',
			'        error = { code: -32601, message: `Method not found: ${name}` };',
			'      }',
			'    } else {',
			'      error = { code: -32601, message: `Method not found: ${req.method}` };',
			'    }',
			'',
			'    if (req.id !== undefined) {',
			'      const response: any = { jsonrpc: "2.0", id: req.id };',
			'      if (error) response.error = error;',
			'      else response.result = result;',
			'      process.stdout.write(JSON.stringify(response) + "\\n");',
			'    }',
			'  } catch {}',
			'});',
		].join("\n");
	}
}
