export class TemplateScaffolder {
	public static getCoreSkills(): Record<string, string> {
		return {
			"skill-harness.md": [
				"# Skill: AI Workflow Harness Meta-Framework",
				"",
				"## Objective",
				"Operate the 2-mode development harness (@planner and stack-specific @builder), executable specs, boundary enforcement, and circuit breaker gates.",
				"",
				"## 1. Core Architecture Invariants",
				"- **2-Mode Operating System:** `@planner` for architectural planning, living spec slicing, and task manifest creation; stack-specific `@builder` for strict TDD task execution.",
				"- **Living Executable Specs:** Replace prose Markdown and ASCII diagrams with TypeScript contracts (`*.contract.ts`) and functional/UI component specs (`*.spec.ts`, `*.spec.tsx`).",
				"- **Atomic Tasks:** Tasks in `.harness/tasks/task-XXX.md` must touch <= 2 implementation code files + 1 test file (max 3 total).",
				"- **Deterministic Verification Gate:** Require test exit code 0 (`harness verify <taskId>`) before setting task status to `DONE`.",
				"- **3-Strike Circuit Breaker:** 3 consecutive test/verification failures trigger automated Git rollback to preflight state.",
				"",
				"## 2. CLI Engines & Workflow Commands",
				"- `harness init` — Scaffold framework tree, agent configurations, tool adapters, skills, and seed SQLite spec database.",
				"- `harness verify <task-id>` — Execute test/lint suite, sanitize error cards, enforce file boundaries, and update status.",
			].join("\n"),

			"skill-caveman.md": [
				"# Skill: Caveman Communication Mode",
				"",
				"## Objective",
				"Ultra-compressed communication mode. Cuts output tokens ~65% while keeping full technical accuracy and code completeness.",
				"",
				"Respond terse like smart caveman. All technical substance stay. Only fluff die.",
				"",
				"## 1. Rules",
				"- Drop articles (a/an/the), filler, pleasantries, hedging.",
				"- Fragments OK. Short synonyms.",
				"- Direct tool calls without narration.",
				"- Preserve technical terms, code, API names, and CLI commands verbatim.",
			].join("\n"),

			"skill-context-caching.md": [
				"# Skill: 2-Level Context Window Caching",
				"",
				"## Objective",
				"Minimize prompt cost across multi-turn agent sessions using structured specification layering.",
				"",
				"## Caching Protocol",
				"1. **Level 1 (Anchor):** Always load `.harness/spec/app-summary.md` into the prompt context on session start.",
				"2. **Level 2 (Demand):** Drill down to `.harness/spec/features/<feature>/README.md` and living specs ONLY when actively implementing that feature.",
				"3. **Zero Unneeded Files:** Never load unreferenced source files or entire directories into the context window.",
			].join("\n"),

			"skill-db-first-specs.md": [
				"# Skill: DB-First Specification Management",
				"",
				"## Objective",
				"Operate the SQLite `.harness/harness.db` spec engine using the native `spec-query` MCP tool to query, insert, and update application specifications.",
				"",
				"## 1. Reading Specs via MCP (`spec-query`)",
				"- **List All Features:** Call `list_features()` to get all registered system features and their status.",
				"- **Get Feature Overview:** Call `get_feature_overview({ featureSlug: \"auth\" })` to inspect summary and topic categories.",
				"- **Get Specific Category Spec:** Call `get_spec({ featureSlug: \"auth\", category: \"business\", level: \"detail\" })`.",
				"- **Search Across Specs:** Call `search_specs({ query: \"jwt token authentication\" })`.",
			].join("\n"),
		};
	}

	public static getStackSkills(): Record<string, string> {
		return {
			"skill-tailwind-shadcn.md": [
				"# Skill: Tailwind CSS & Component Architecture",
				"",
				"## Rules & Invariants",
				"- Use utility-first Tailwind classes adhering strictly to established design system tokens.",
				"- Maintain accessibility attributes (`aria-*`, `role`, focus visible states) across all interactive elements.",
				"- Keep presentation logic separate from custom data hooks.",
				"- Support seamless dark mode and glassmorphism styling.",
			].join("\n"),

			"skill-tanstack-query.md": [
				"# Skill: TanStack Query Best Practices",
				"",
				"## Rules & Invariants",
				"- Declare standardized query keys using array tuples `['resource', id]`.",
				"- Implement optimistic updates for mutating actions with automatic rollback on error.",
				"- Centralize API fetchers in dedicated service modules with typed responses.",
			].join("\n"),

			"skill-expo-router.md": [
				"# Skill: Expo Router & React Native Architecture",
				"",
				"## Rules & Invariants",
				"- Follow file-based routing conventions inside `app/` directory.",
				"- Utilize `react-native-reanimated` for smooth 60fps UI transitions.",
				"- Ensure safe area insets are respected across iOS and Android viewports.",
			].join("\n"),

			"skill-typescript-strict.md": [
				"# Skill: Strict TypeScript & Zod Type Safety",
				"",
				"## Rules & Invariants",
				"- Enforce `strict: true` with ZERO usage of `any` (use `unknown` + type guards).",
				"- Derive runtime types from Zod schemas using `z.infer<typeof Schema>`.",
				"- Use discriminated unions for distinct application state representations.",
				"- Maintain explicit return types on all public export functions.",
			].join("\n"),

			"skill-idiomatic-go.md": [
				"# Skill: Idiomatic Golang Architecture",
				"",
				"## Rules & Invariants",
				"- Always accept `context.Context` as the first argument in I/O and database methods.",
				"- Explicitly wrap errors using `fmt.Errorf(\"action: %w\", err)`.",
				"- Use structured logging via standard library `log/slog`.",
			].join("\n"),

			"skill-sqlc.md": [
				"# Skill: sqlc Type-Safe SQL Queries",
				"",
				"## Rules & Invariants",
				"- Author pure SQL queries with annotated query names `-- name: GetUser :one`.",
				"- Run `sqlc generate` to produce type-safe Go structs without ORM overhead.",
			].join("\n"),

			"skill-postgres-schema-design.md": [
				"# Skill: PostgreSQL Schema & Migration Strategy",
				"",
				"## Rules & Invariants",
				"- All foreign keys must include explicit index coverage.",
				"- Author migrations with deterministic down/rollback scripts.",
				"- Use `TIMESTAMPTZ` for all temporal columns.",
			].join("\n"),

			"skill-dynamodb-single-table.md": [
				"# Skill: DynamoDB Single-Table Design",
				"",
				"## Rules & Invariants",
				"- Model access patterns before defining Partition (`PK`) and Sort (`SK`) keys.",
				"- Use composite sort keys with delimiters (e.g. `USER#123#METADATA`).",
			].join("\n"),
		};
	}

	public static getTestingSkills(): Record<string, string> {
		return {
			"skill-executable-specs.md": [
				"# Skill: Living Executable Specifications",
				"",
				"## Objective",
				"Author executable TypeScript contracts (*.contract.ts) and component specifications (*.spec.ts, *.spec.tsx) that serve as living system documentation.",
				"",
				"## Rules & Invariants",
				"- Define type contracts using strict Zod schemas or TypeScript interfaces.",
				"- Do NOT write prose markdown specs when executable contracts can be written.",
				"- Keep spec files colocated or linked from feature manifests.",
			].join("\n"),

			"skill-ui-contracts.md": [
				"# Skill: UI Component Contracts & Spec Declarations",
				"",
				"## Objective",
				"Define component prop interfaces, visual state invariants, and layout contracts using functional TypeScript specs.",
				"",
				"## Rules & Invariants",
				"- Author component state trees using typed prop contracts.",
				"- Avoid ASCII block wireframes — declare visual layouts using structured JSX/TSX prop specs.",
			].join("\n"),

			"skill-tdd-assertions.md": [
				"# Skill: Test-Driven Development (TDD) Assertions",
				"",
				"## Objective & Discipline",
				"Author comprehensive, failing test suites BEFORE any implementation code begins (RED phase of TDD).",
				"",
				"## Mandatory Assertion Rules",
				"1. **Happy Path:** Assert specific expected return values, payload structures, and side effects.",
				"2. **Sad Path FIRST:** Error handling is more important than happy path. Test invalid input rejection using specific error matchers (e.g. `toThrow()`).",
				"3. **No Soft Assertions:** Never use `toBeTruthy()` or `toBeDefined()` alone — assert exact values.",
				"4. **Isolation:** Mock external dependencies (filesystem, network, DB) — tests must run deterministically in isolated sandbox.",
			].join("\n"),

			"skill-zero-noise-reporter.md": [
				"# Skill: Zero-Noise Test Diagnostic Reporting",
				"",
				"## Objective",
				"Format test failures into concise, actionable diagnostic cards to prevent log pollution.",
			].join("\n"),
		};
	}

	public static getPipelineStandards(): Record<string, string> {
		return {
			"summary.md": [
				"# Lean 2-Mode AI Workflow Standards",
				"",
				"> **Living Specs, Boundary-Isolated Tasks & Deterministic Gates**",
				"",
				"## Operating Modes",
				"- **@planner:** Reasoning agent for architectural planning, living spec slicing (*.contract.ts, *.spec.ts, *.spec.tsx), and task manifest creation (.harness/tasks/task-XXX.md). Never writes application code.",
				"- **@builder:** Stack-specific TDD executor (e.g. @web-builder, @mobile-builder, @backend-builder). Implements tasks test-first (RED -> GREEN -> REFACTOR) strictly within allowed file boundaries.",
				"",
				"## Execution Invariants",
				"1. **Atomic Tasks:** Max 2 implementation code files + 1 test file (max 3 total) per task.",
				"2. **Living Executable Specs:** Contract & spec definitions replace prose design documents.",
				"3. **Deterministic Verification Gate:** Run `harness verify <taskId>` to enforce boundaries, run tests, and trigger circuit breaker rollbacks on failures.",
			].join("\n"),
		};
	}

	public static getUIComponentRegistryStarter(): string {
		return [
			"export interface UIComponentRecord {",
			"  name: string;",
			'  category: "atom" | "molecule" | "organism" | "template";',
			"  location: string;",
			"  description: string;",
			"  propsInterface?: string;",
			"  subComponents?: string[];",
			"  reusableAcross: string[];",
			"}",
			"",
			"export const CustomComponentsRegistry: UIComponentRecord[] = [];",
			"",
		].join("\n");
	}

	public static getRolesJson(): string {
		return JSON.stringify(
			{
				planner: {
					role: "planner",
					allowedTools: ["*"],
					allowedCategories: ["technical", "pipeline", "business", "tasks"],
				},
				builder: {
					role: "builder",
					allowedTools: ["*"],
					allowedCategories: ["tasks"],
				},
			},
			null,
			2,
		);
	}

	public static getCheckpointDbScript(): string {
		return [
			'import { Database } from "bun:sqlite";',
			'import path from "node:path";',
			"",
			'const dbPath = path.resolve(process.cwd(), ".harness/harness.db");',
			"const db = new Database(dbPath);",
			'db.exec("PRAGMA wal_checkpoint(TRUNCATE);");',
			"db.close();",
			'console.log("✔ harness.db WAL checkpoint complete (TRUNCATE).");',
		].join("\n");
	}

	public static getSeedFeaturesScript(): string {
		return [
			'import { Database } from "bun:sqlite";',
			'import fs from "node:fs/promises";',
			'import path from "node:path";',
			"",
			"async function seedFromDocs() {",
			'  const dbPath = path.resolve(process.cwd(), ".harness/harness.db");',
			"  const db = new Database(dbPath);",
			'  const docsDir = path.resolve(process.cwd(), "docs");',
			"  try {",
			"    const files = await fs.readdir(docsDir);",
			"    for (const file of files) {",
			'      if (file.endsWith(".md")) {',
			"        const raw = await fs.readFile(path.join(docsDir, file), \"utf-8\");",
			'        const slug = file.replace(".md", "").toLowerCase().replace(/[^a-z0-9]/g, "-");',
			'        const title = file.replace(".md", "");',
			'        const stmt = db.prepare("INSERT OR REPLACE INTO features (id, name, slug, summary, status) VALUES (?, ?, ?, ?, ?)");',
			'        stmt.run(`feat-${slug}`, title, slug, raw.slice(0, 150).replace(/\\n/g, " "), "STABLE");',
			"      }",
			"    }",
			"  } catch {}",
			'  db.exec("DELETE FROM spec_topics WHERE id NOT IN (SELECT DISTINCT topic_id FROM spec_chunks);");',
			'  db.exec("DELETE FROM features WHERE id NOT IN (SELECT DISTINCT feature_id FROM spec_topics);");',
			'  db.exec("PRAGMA wal_checkpoint(TRUNCATE);");',
			"  db.close();",
			'  console.log("✔ Seeded features to harness.db.");',
			"}",
			"seedFromDocs();",
		].join("\n");
	}

	public static getMigrateSpecsScript(): string {
		return [
			'import { Database } from "bun:sqlite";',
			'import fs from "node:fs/promises";',
			'import path from "node:path";',
			"",
			"async function migrateSpecs() {",
			'  const dbPath = path.resolve(process.cwd(), ".harness/harness.db");',
			"  const db = new Database(dbPath);",
			'  const specDir = path.resolve(process.cwd(), ".harness/spec/features");',
			"  try {",
			"    const featDirs = await fs.readdir(specDir);",
			"    for (const slug of featDirs) {",
			"      const featPath = path.join(specDir, slug);",
			"      const stat = await fs.stat(featPath);",
			"      if (stat.isDirectory()) {",
			'        for (const cat of ["business", "ui", "technical"] as const) {',
			'          const specFile = path.join(featPath, cat, "spec.md");',
			"          try {",
			'            const content = await fs.readFile(specFile, "utf-8");',
			'            const featRow = db.prepare("SELECT id FROM features WHERE slug = ?").get(slug) as any;',
			"            if (featRow) {",
			'              const topicId = `topic-${slug}-${cat}`;',
			'              db.prepare("INSERT OR REPLACE INTO spec_topics (id, feature_id, category, slug, title) VALUES (?, ?, ?, ?, ?)").run(topicId, featRow.id, cat, cat, `${cat} Spec`);',
			'              db.prepare("INSERT OR REPLACE INTO spec_chunks (id, topic_id, level, content, token_estimate) VALUES (?, ?, ?, ?, ?)").run(`chunk-${topicId}-detail`, topicId, "detail", content, Math.ceil(content.length / 4));',
			"            }",
			"          } catch {}",
			"        }",
			"      }",
			"    }",
			"  } catch {}",
			'  db.exec("DELETE FROM spec_topics WHERE id NOT IN (SELECT DISTINCT topic_id FROM spec_chunks);");',
			'  db.exec("DELETE FROM features WHERE id NOT IN (SELECT DISTINCT feature_id FROM spec_topics);");',
			'  db.exec("PRAGMA wal_checkpoint(TRUNCATE);");',
			"  db.close();",
			'  console.log("✔ Migrated specs into harness.db.");',
			"}",
			"migrateSpecs();",
		].join("\n");
	}

	public static getSpecQueryMcpServer(): string {
		return [
			'import { Database } from "bun:sqlite";',
			'import path from "node:path";',
			'import readline from "node:readline";',
			"",
			'const dbPath = path.resolve(process.cwd(), ".harness/harness.db");',
			"const db = new Database(dbPath);",
			"",
			"function checkpoint() {",
			'  try { db.exec("PRAGMA wal_checkpoint(TRUNCATE);"); } catch {}',
			"}",
			"",
			"const rl = readline.createInterface({",
			"  input: process.stdin,",
			"  output: process.stdout,",
			"  terminal: false,",
			"});",
			"",
			'rl.on("line", (line) => {',
			"  if (!line.trim()) return;",
			"  try {",
			"    const req = JSON.parse(line);",
			'    if (!req.id && req.method === "notifications/initialized") return;',
			"",
			"    let result: any = null;",
			"    let error: any = null;",
			"",
			'    if (req.method === "initialize") {',
			"      result = {",
			'        protocolVersion: "2024-11-05",',
			'        capabilities: { tools: {} },',
			'        serverInfo: { name: "spec-query", version: "2.0.0" },',
			"      };",
			'    } else if (req.method === "tools/list") {',
			"      result = {",
			"        tools: [",
			"          {",
			'            name: "list_features",',
			'            description: "List all registered system features and their status from SQLite spec database.",',
			'            inputSchema: { type: "object", properties: {} },',
			"          },",
			"          {",
			'            name: "get_feature_overview",',
			'            description: "Get summary and registered spec topics for a specific feature by slug.",',
			"            inputSchema: {",
			'              type: "object",',
			'              properties: { featureSlug: { type: "string", description: "Feature slug identifier" } },',
			'              required: ["featureSlug"],',
			"            },",
			"          },",
			"          {",
			'            name: "get_spec",',
			'            description: "Retrieve specification content for a feature by category (business, ui, technical, pipeline) and detail level.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                featureSlug: { type: "string", description: "Feature slug identifier" },',
			'                category: { type: "string", enum: ["business", "ui", "technical", "pipeline"] },',
			'                level: { type: "string", enum: ["summary", "detail"], default: "detail" },',
			"              },",
			'              required: ["featureSlug", "category"],',
			"            },",
			"          },",
			"          {",
			'            name: "search_specs",',
			'            description: "Perform full-text search across all spec topics and chunks in SQLite spec database.",',
			"            inputSchema: {",
			'              type: "object",',
			'              properties: { query: { type: "string", description: "Search query string" } },',
			'              required: ["query"],',
			"            },",
			"          },",
			"          {",
			'            name: "write_spec",',
			'            description: "Author or update a specification topic and chunk in SQLite spec database with auto WAL checkpointing.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                featureSlug: { type: "string", description: "Target feature slug" },',
			'                category: { type: "string", enum: ["business", "ui", "technical", "pipeline"] },',
			'                topicSlug: { type: "string", description: "Topic slug" },',
			'                title: { type: "string", description: "Topic title" },',
			'                content: { type: "string", description: "Specification markdown content" },',
			'                level: { type: "string", enum: ["summary", "detail"], default: "detail" },',
			"              },",
			'              required: ["featureSlug", "category", "topicSlug", "title", "content"],',
			"            },",
			"          },",
			"          {",
			'            name: "update_feature_status",',
			'            description: "Update the status of a registered feature in SQLite spec database.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                featureSlug: { type: "string", description: "Target feature slug" },',
			'                status: { type: "string", enum: ["DRAFT", "STABLE", "DEPRECATED"] },',
			"              },",
			'              required: ["featureSlug", "status"],',
			"            },",
			"          },",
			"          {",
			'            name: "create_task",',
			'            description: "Create a boundary-isolated task manifest entry in SQLite spec database.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                taskId: { type: "string", description: "Task ID (e.g. task-authlogin)" },',
			'                specSlug: { type: "string", description: "Associated feature slug" },',
			'                status: { type: "string", enum: ["TODO", "IN_PROGRESS", "VERIFYING", "DONE"], default: "TODO" },',
			'                allowedFiles: { type: "string", description: "Comma-separated allowed files (max 2)" },',
			'                acceptanceCriteria: { type: "string", description: "Acceptance criteria markdown checklist" },',
			"              },",
			'              required: ["taskId", "allowedFiles", "acceptanceCriteria"],',
			"            },",
			"          },",
			"          {",
			'            name: "update_task_status",',
			'            description: "Update task status in SQLite spec database.",',
			"            inputSchema: {",
			'              type: "object",',
			"              properties: {",
			'                taskId: { type: "string", description: "Target task ID" },',
			'                status: { type: "string", enum: ["TODO", "IN_PROGRESS", "VERIFYING", "DONE"] },',
			"              },",
			'              required: ["taskId", "status"],',
			"            },",
			"          },",
			"        ],",
			"      };",
			'    } else if (req.method === "tools/call") {',
			"      const name = req.params?.name;",
			"      const args = req.params?.arguments || {};",
			'      if (name === "list_features") {',
			'        const rows = db.prepare("SELECT id, name, slug, summary, status FROM features ORDER BY name").all();',
			'        result = { content: [{ type: "text", text: JSON.stringify(rows, null, 2) }] };',
			'      } else if (name === "get_feature_overview") {',
			'        const slug = String(args?.featureSlug);',
			'        const feature = db.prepare("SELECT * FROM features WHERE slug = ?").get(slug);',
			'        if (!feature) {',
			'          result = { content: [{ type: "text", text: `Feature slug "${slug}" not found.` }] };',
			'        } else {',
			'          const topics = db.prepare("SELECT id, category, slug, title FROM spec_topics WHERE feature_id = (SELECT id FROM features WHERE slug = ?)").all(slug);',
			'          result = { content: [{ type: "text", text: JSON.stringify({ feature, topics }, null, 2) }] };',
			'        }',
			'      } else if (name === "get_spec") {',
			'        const slug = String(args?.featureSlug);',
			'        const category = String(args?.category);',
			'        const level = String(args?.level || "detail");',
			'        const query = db.prepare(`',
			'          SELECT t.title, t.category, c.level, c.content FROM spec_chunks c',
			'          JOIN spec_topics t ON c.topic_id = t.id',
			'          JOIN features f ON t.feature_id = f.id',
			'          WHERE f.slug = ? AND (t.category = ? OR t.slug = ?) AND c.level = ?',
			'        `);',
			'        const rows = query.all(slug, category, category, level);',
			'        if (!rows.length) {',
			'          result = { content: [{ type: "text", text: `No ${level} specs found for ${slug}/${category}.` }] };',
			'        } else {',
			'          result = { content: [{ type: "text", text: JSON.stringify(rows, null, 2) }] };',
			'        }',
			'      } else if (name === "search_specs") {',
			'        const q = `%${String(args?.query)}%`;',
			'        const rows = db.prepare(`',
			'          SELECT f.name as feature, t.category, t.title, c.content FROM spec_chunks c',
			'          JOIN spec_topics t ON c.topic_id = t.id',
			'          JOIN features f ON t.feature_id = f.id',
			'          WHERE t.title LIKE ? OR c.content LIKE ?',
			'          LIMIT 20',
			'        `).all(q, q);',
			'        result = { content: [{ type: "text", text: JSON.stringify(rows, null, 2) }] };',
			'      } else if (name === "write_spec") {',
			'        const slug = String(args?.featureSlug);',
			'        const category = String(args?.category);',
			'        const topicSlug = String(args?.topicSlug);',
			'        const title = String(args?.title);',
			'        const content = String(args?.content);',
			'        const level = String(args?.level || "detail");',
			'        const feat = db.prepare("SELECT id FROM features WHERE slug = ?").get(slug) as any;',
			'        if (!feat) {',
			'          result = { content: [{ type: "text", text: `Error: Feature "${slug}" not found in database.` }] };',
			'        } else {',
			'          const topicId = `topic-${slug}-${topicSlug}`;',
			'          db.prepare("INSERT OR REPLACE INTO spec_topics (id, feature_id, category, slug, title) VALUES (?, ?, ?, ?, ?)").run(topicId, feat.id, category, topicSlug, title);',
			'          db.prepare("INSERT OR REPLACE INTO spec_chunks (id, topic_id, level, content, token_estimate) VALUES (?, ?, ?, ?, ?)").run(`chunk-${topicId}-${level}`, topicId, level, content, Math.ceil(content.length / 4));',
			'          checkpoint();',
			'          result = { content: [{ type: "text", text: `✔ Successfully wrote spec for ${slug}/${category}/${topicSlug} (WAL checkpointed).` }] };',
			'        }',
			'      } else if (name === "update_feature_status") {',
			'        const slug = String(args?.featureSlug);',
			'        const status = String(args?.status);',
			'        db.prepare("UPDATE features SET status = ? WHERE slug = ?").run(status, slug);',
			'        checkpoint();',
			'        result = { content: [{ type: "text", text: `✔ Updated feature "${slug}" status to ${status}.` }] };',
			'      } else if (name === "create_task") {',
			'        const taskId = String(args?.taskId);',
			'        const specSlug = String(args?.specSlug || "");',
			'        const status = String(args?.status || "TODO");',
			'        const allowedFiles = String(args?.allowedFiles);',
			'        const acceptanceCriteria = String(args?.acceptanceCriteria);',
			'        const feat = specSlug ? (db.prepare("SELECT id FROM features WHERE slug = ?").get(specSlug) as any) : null;',
			'        db.prepare("INSERT OR REPLACE INTO tasks (id, spec_id, status, allowed_files, acceptance_criteria) VALUES (?, ?, ?, ?, ?)").run(taskId, feat?.id || null, status, allowedFiles, acceptanceCriteria);',
			'        checkpoint();',
			'        result = { content: [{ type: "text", text: `✔ Task "${taskId}" created/updated in database.` }] };',
			'      } else if (name === "update_task_status") {',
			'        const taskId = String(args?.taskId);',
			'        const status = String(args?.status);',
			'        db.prepare("UPDATE tasks SET status = ? WHERE id = ?").run(status, taskId);',
			'        checkpoint();',
			'        result = { content: [{ type: "text", text: `✔ Updated task "${taskId}" status to ${status}.` }] };',
			'      } else {',
			'        error = { code: -32601, message: `Method not found: ${name}` };',
			'      }',
			'    } else {',
			'      error = { code: -32601, message: `Method not found: ${req.method}` };',
			'    }',
			'',
			'    if (req.id !== undefined) {',
			'      const response: any = { jsonrpc: "2.0", id: req.id };',
			'      if (error) response.error = error;',
			'      else response.result = result;',
			'      process.stdout.write(JSON.stringify(response) + "\\n");',
			'    }',
			'  } catch {}',
			'});',
		].join("\n");
	}
}
